on: [push, pull_request]
name: Continuous integration
jobs:
  test:
    name: run tests and linters
    uses: kubewarden/github-actions/.github/workflows/reusable-test-policy-go.yml@0f1672d63bd3572f204917d68390d87f7430069a # v5.0.0
