on: [push, pull_request]
name: Continuous integration
jobs:
  test:
    name: run tests and linters
    uses: kubewarden/github-actions/.github/workflows/reusable-test-policy-go.yml@a1c3c24660e1a2f945efdadc6306ea3e83ddfed8 # v5.0.2
