on: [push, pull_request]
name: Continuous integration
jobs:
  test:
    name: run tests and linters
    uses: kubewarden/github-actions/.github/workflows/reusable-test-policy-go.yml@ff49d7af0447a59fe9a58a82805713e1a25539f2 # v4.6.2
